### ISSUE TITLE
help adding resources

### ISSUE THREAD

**Issue by dpastoor** [dpastoor/awesome-shiny#1]
Hi @daattali any interest in helping pull together a list of reasonably recent resources (at least your stuff!)

**Comment by daattali** [comment]
Hi, thanks for reaching out! I'll let you deal with organizing these into their proper sections (also because I don't want the headache of doing it :smile: ), but here's a bunch of links I think are useful. Many of them are my own stuff but I do try to make things generally applicable, so feel free to only include the ones you agree are useful. Also, great idea doing this, I think it's very much needed!

Maybe add sections for Shiny Server and shinyapps?
- [Sending data from Shiny to JavaScript and vice versa](https://ryouready.wordpress.com/2013/11/20/sending-data-from-client-to-server-and-back-using-shiny/)
- [Shiny articles](http://shiny.rstudio.com/articles/) has an extremely useful selection of excellent articles, I strongly urge everyone to go through most of them eventually (although this will be the third link to shiny.rstudio.com, so maybe it's a bit redundant)
- [How to get your own Shiny Server on the cloud to host your apps](http://deanattali.com/2015/05/09/setup-rstudio-shiny-server-digital-ocean/)
- [showmeshiny](http://www.showmeshiny.com/) - a huge gallery of Shiny apps
- [shinyapps google group](https://groups.google.com/forum/#!forum/shinyapps-users)
- [Shiny Server documentation](http://rstudio.github.io/shiny-server/latest/)
- [StackOverflow shiny questions](http://stackoverflow.com/questions/tagged/shiny)
- [R-bloggers shiny articles](http://www.r-bloggers.com/search/shiny)
- [Blog post: Mimicking a Google Form with a shiny app](http://deanattali.com/2015/06/14/mimicking-google-form-shiny/)
- [Blog post: Persistent data storage (and retrieval) in Shiny apps](http://deanattali.com/blog/shiny-persistent-data-storage/)
- [App: saving and restoring session state of a shiny app (Joe Cheng)](https://github.com/jcheng5/shiny-resume)
- [GitHub repo: setup of a sample Shiny Server, with the config files and sample apps included](https://github.com/daattali/shiny-server)

edit:
- I forgot about [shinydashboard](http://rstudio.github.io/shinydashboard/)
- [Popups in shiny (Joe Cheng gist)](https://gist.github.com/jcheng5/5913297)

**Comment by dpastoor** [comment]
sweet - I will add these (thanks for collecting them). I knew you had a bunch of stuff so figured you'd be faster finding/dumping it than me searching through. Feel free to ping anyone else that may have additional resources. Else I'll just start munging through with github-wide and google searches until it (hopefully) gains some traction and people add pull requests for material they create.

**Comment by daattali** [comment]
maybe post on the google group telling people to make pull requests if they think they have a hig hquality resource that will be useful for others

**Comment by dpastoor** [comment]
i like it - good call

**Comment by dpastoor** [comment]
added in 55d72d07310b7ff6a167614f6405d29962a69a13
